### ISSUE TITLE
FileBrowser: Todo's

### ISSUE THREAD

**Issue by Splamy** [ReSpeak/Qint#26]
- [ ] Ctrl + X / V
- [x] Drag and Drop move
- [ ] Rename File
- [x] Keep sort on refres (and correct sort on load)
- [ ] Prevent click after doubleclick open folder
- [ ] Ask on override
- [ ] Resume down/upload
- [ ] Move transfermanager out of component
